In [1]:
import pandas as pd
import numpy as np
import datetime
from ocean_gases import ocean_gases as og

In [2]:
data = pd.read_csv('/home/ashao/data/glodap/GLODAPv2.2019_Merged_Master_File.csv')
data['datetime'] = [ datetime.datetime(int(pack[0]), int(pack[1]), int(pack[2])) for pack in zip(data['year'],data['month'],data['day']) ]
data['yearfrac'] = [ date.year + date.dayofyear/(datetime.datetime(date.year,12,31)-datetime.datetime(date.year,1,1)).days for date in data['datetime'] ]

In [3]:
subdata = data[data.pcfc11 != -9999].iloc[range(100,200)]
subdata.head()

,cruise,station,cast,year,month,day,hour,minute,latitude,longitude,...,doc,docf,don,donf,tdn,tdnf,chla,chlaf,datetime,yearfrac
250,1.0,333.0,1.0,1984.0,7.0,27.0,6.0,9.0,82.27,-8.6667,...,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,1984-07-27,1984.572603
251,1.0,333.0,1.0,1984.0,7.0,27.0,6.0,9.0,82.27,-8.6667,...,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,1984-07-27,1984.572603
252,1.0,333.0,1.0,1984.0,7.0,27.0,6.0,9.0,82.27,-8.6667,...,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,1984-07-27,1984.572603
253,1.0,333.0,1.0,1984.0,7.0,27.0,6.0,9.0,82.27,-8.6667,...,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,1984-07-27,1984.572603
254,1.0,333.0,1.0,1984.0,7.0,27.0,6.0,9.0,82.27,-8.6667,...,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,-9999.0,9.0,1984-07-27,1984.572603

In [4]:
importlib.reload(og)
subdata['cfc11_age'] = [ og.ttdmatch(row.pcfc11,row.datetime,'cfc11',sat=0.85,lat=row.latitude,verbose=True) for idx, row in subdata.iterrows() ]

NameError: name 'importlib' is not defined